### ISSUE TITLE
other_certificates is not pulling all certs in file

### ISSUE THREAD

**Issue by krobertson71** [ansible-collections/community.crypto#149]
Here is my ansible cfg

  - name: Generate PFX file
    become: yes
   become_user: "{{ app_user }}"
    community.crypto.openssl_pkcs12:
      action: export
      path: "{{ sslpath }}/{{ fqdn_v }}/{{ fqdn_v }}.pfx"
      friendly_name: "{{ fqdn_v }}"
      privatekey_path: "{{ sslpath }}/{{ fqdn_v }}/{{ fqdn_v }}.key"
      certificate_path: "{{ sslpath }}/{{ fqdn_v }}/{{ fqdn_v }}.crt"
      **other_certificates: "{{ sslpath }}/{{ fqdn_v}}/{{ InCommon_crt }}"**
      passphrase: "{{ pfx_pass }}"
      state: present
      mode: "0644"

the "InCommon_crt" contains the whole chain, but when it goes and reads the .crt it only pulls the first certificate entry it finds:

There are 3 sets of certs in the InCommon.crt file.  

All being and end with:

-----BEGIN CERTIFICATE-----

-----END CERTIFICATE-----

**Comment by krobertson71** [comment]
I did manage a workaround by breaking the chain cert into 3 different certs and was able to load them all with "other_certificates".  Would like for the module to pull all 3 certs from the original file if possible.

**Comment by felixfontein** [comment]
If someone is interested in implementing this, here's some code which could be used: https://github.com/ansible-collections/community.crypto/blob/main/plugins/modules/certificate_complete_chain.py#L192-L218 It probably makes sense to refactor this to have a function which splits a string into a list of strings, each containing one certificate.

**Comment by felixfontein** [comment]
resolved_by_pr #166
