### ISSUE TITLE
Make it possible to generate a certificate, with ACME, without exporting the account’s private key to the target machine.

### ISSUE THREAD

**Issue by nboullis** [ansible-collections/community.crypto#151]
##### SUMMARY

Make it possible to generate a certificate, with ACME, without exporting the account’s private key to the target machine.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

acme_certificate

##### ADDITIONAL INFORMATION

I’m willing to use ansible to create certificates on server installation, and then to renew them.

I have an ACME account with a CA that uses external account binding. That account is pre-authorized for the domain I manage and its subdomains.

I am concerned that `acme_certificate`, as I understand it, would export the account’s private key to any target that needs a certificate. Some target have low trust, or might have been compromised. I’d rather not take the risk to have my account’s private key compromised, as the attacker might then be able to get certificates for any name of my domain.

I think it would be great if it were possible for the `acme_certificate` module to perform the required signatures on ansible server rather than on the target. As I understand it, it would require to rewrite that module as an Action plug-in

Any opinion on this?

**Comment by felixfontein** [comment]
Why do you need to run `acme_certificate` on the remote machine if you don't want to send the key there? The module is designed to do the parts of the ACME protocol that require only some information on the certificate requested (namely the CSR) and the account key. Everything else that is about updating DNS values or updating files on a remote server needs to be done separately. So it should be run on exactly the machine which has the key (usually `localhost`, maybe something else depending on your specific situation), and not on any other machine.

**Comment by nboullis** [comment]
Hmmm… Looks like I missed something, I am quite new to Ansible… You mean it is possible, for example within a role, to generate a CSR on the target, fetch it, run the `acme_certificate` module on localhost and then copy the certificate to the target?

**Comment by felixfontein** [comment]
Yes, if you want the private key never to leave the target, that's the way to go. You need to run the `acme_certificate` module twice though, and do something to validate the challenges inbetween, though.

**Comment by felixfontein** [comment]
See some of the examples: https://docs.ansible.com/ansible/latest/collections/community/crypto/acme_certificate_module.html#examples

For less complicated cases (you have both account key and private key for certificate on localhost), you can also use existing roles such as https://github.com/felixfontein/acme-certificate/

**Comment by nboullis** [comment]
Thanks a lot for your help. I could sort this out using `local_action`. I had somehow missed this option (and the `delegate_to` option). Sorry for the trouble. My request was nonsense. Closing it now.

**Comment by felixfontein** [comment]
No problem! Feel free to ask if you have other questions / problems when using the module. It is more complicated to use than most other ACME clients, but it offers a lot of flexibility :)
