### ISSUE TITLE
Add crypto information module

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.crypto#169]
##### SUMMARY
I think it would be helpful to have a _info module which tells the user some properties of the cryptographic libraries used by the detected backend (pyOpenSSL or cryptography), for example:
- which ECC curves are available;
- which hash functions are available (for fingerprints);
- which version of cryptography and/or pyOpenSSL is available;
- which underlying OpenSSL version is used (if available), and information on the OpenSSL binary found on the path (version, type, ...).

What do you think? Is this useful? What other information would you like?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
crypto_info

**Comment by MarkusTeufelberger** [comment]
Might be useful for developing, testing and debugging (e.g. asking users to show the output of this module in bug reports or run it on various platforms to make sure CI uses real world versions), I'm not so sure if there's some actual benefit for users of this collection beyond that.

There's already something like this in the tests, so there might be some small benefits there already and module_utils also have quite large feature detection settings that are not really exposed, so there might be some better insights for users possible with this.

**Comment by felixfontein** [comment]
I've implemented a first version (which gives feedback on the installed `cryptography` version) in #363.
