### ISSUE TITLE
luks_device: make key add/removal idempotent

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.crypto#19]
##### SUMMARY
* The `new_keyfile` currently adds a new key, no matter whether the key is already present or not.
* The `remove_keyfile` currently dies when the key is not present.

To implement this properly (especially with #52371, `allow_to_remove_last_key`, in mind), we need a mechanism which can detect if a key is already there. If the device is closed, one could try to open it (and on success close it again); that would probably be an acceptable hack. That doesn't work when the device is already open, though.

(Migration of ansible/ansible#52409; existing PR ansible/ansible#65937, CC @mulatinho)

##### COMPONENT NAME
luks_device

##### ISSUE TYPE
- Feature Idea

**Comment by felixfontein** [comment]
@mulatinho would be great if you could migrate the PR to this collection! If you need help, just ask :)

**Comment by mulatinho** [comment]
@felixfontein  hey! lots of things changed here :D I really want to participate more, I think now I am fully established on my new company and probably I will have more time! I will try to see how things are working now here and try finally work more on the group, thanks for reminder me!
