### ISSUE TITLE
openssl_pkcs12: add cryptography backend

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.crypto#21]
##### SUMMARY
The `openssl_pkcs12` module should support a cryptography backend, so PyOpenSSL can be deprecated / removed eventually. Currently cryptography does not support PKCS12, though, so some preliminary work on adding PKCS12 support to cryptography is needed. Also, this means that deprecating the PyOpenSSL backend would need to be done much later than for other modules, since a new enough cryptography supporting the new features (which aren't there yet) will take some years to trickle through.

(Migration of ansible/ansible#59905)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
openssl_pkcs12

**Comment by felixfontein** [comment]
cryptography has now basic PKCS12 suport: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#pkcs12

It seems to be too limited for what the openssl_pkcs12 module offers, though, so it's not usable for us yet.

**Comment by MarkusTeufelberger** [comment]
Looks like it was added in https://github.com/pyca/cryptography/pull/5325 to cryptography. Let's hope they expand on it.

**Comment by felixfontein** [comment]
What's currently missing to replicate the current behavior is the ability to read the 'friendly name' from the PKCS#12 file. I've created pyca/cryptography#5760 for that.

**Comment by felixfontein** [comment]
resolved_by #234.
