### ISSUE TITLE
Strange error for modules importing pyOpenSSL when Ansible just upgraded cryptography on controller

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.crypto#23]
##### SUMMARY
See ansible/ansible#68701 and ansible-collections/community.crypto#22 for details.

This affects everything importing module_utils/crypto.py in collections.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
get_certificate
openssl_*

##### ANSIBLE VERSION
```paste below
2.9
devel
```

**Comment by felixfontein** [comment]
Simplified reproducer: ansible-collections/community.crypto#22

**Comment by felixfontein** [comment]
TODO: When this is fixed, re-enable consul tests in community.general (ansible-collections/community.general#117)

**Comment by MarkusTeufelberger** [comment]
Maybe we should just vendor all our dependencies (at least the Python ones) in here and be done with it? That way we could also deprecate pyOpenSSL immediately...

**Comment by felixfontein** [comment]
I'm not sure whether that will make our life easier, since cryptography comes with some binary components which depend on the system where it is installed. The only pure-Python dependencies are ipaddress and pyOpenSSL, and the latter depends on a new enough version of cryptography.

Anyway, this issue is about a bug in Ansible itself, which should get fixed eventually. And then this specific problem will go away. (Not all other cryptography/pyOpenSSL problems, of course :) )

**Comment by MarkusTeufelberger** [comment]
Urgh, at some point I'm more and more leaning towards writing this in go or rust and statically compiling it for Linux. How's the support for binary modules in collections? Probably not even that bad I guess...

**Comment by bcoca** [comment]
they work just like any other module

**Comment by felixfontein** [comment]
This will be finally fixed once the routing/tombstoning PR is merged.
