### ISSUE TITLE
Next planned release: 2.1.0

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.crypto#321]
- [x] https://github.com/ansible-collections/community.crypto/pull/363: Add basic crypto_info module
- [ ] https://github.com/ansible-collections/community.crypto/pull/362: Add openssl_privatekey_convert module

**Comment by felixfontein** [comment]
I'd like to make a new release by Tuesday, so that the current bugfixes get into the next Ansible 5 release.

**Comment by briantist** [comment]
I use the [Milestones](https://github.com/ansible-collections/community.crypto/milestones) feature in GitHub to track stuff like this. Each new expected version has a milestone, you can optionally add a description and due date. Issues and PRs can have the selected milestone chosen on the side. The milestone then automatically shows a progress bar based on the which are closed vs. open.

https://github.com/ansible-collections/community.hashi_vault/milestones

**Comment by felixfontein** [comment]
Milestones are nice, but you can't add comments :) It's probably still a good idea to use them. I guess discussions are more important for major releases (i.e. 3.0.0) than for 'regular' minor ones.

**Comment by briantist** [comment]
> Milestones are nice, but you can't add comments :)

Ah that is true! I don't have strong feelings about how anyone else does it, just figured I'd share :)

**Comment by felixfontein** [comment]
The 2.1.0 release is in progress. The next planning issue is #375 for 2.2.0.
