### ISSUE TITLE
Module luks_device: adding a key not possible on other Linux locales

### ISSUE THREAD

**Issue by liglury-jr** [ansible-collections/community.crypto#385]
https://github.com/ansible-collections/community.crypto/blob/a467f036b1c8c5b35bce9f2d7bace69073c17468/plugins/modules/luks_device.py#L642

Adding a new key (new_keyfile) does not work on other locales!

When adding a new key to luks the stdout of --test-passphrase is evaluated only in english. See line number above.
This leads to an error an no key is added.

Example:
    name: Add new key to the LUKS container (container has to exist)
    community.crypto.luks_device:
    device: "/dev/loop0"
    keyfile: "/vault/keyfile"
    new_keyfile: "/vault/keyfile2"

**Comment by felixfontein** [comment]
Thanks for reporting this! It could be that doing something like https://github.com/ansible-collections/community.general/blob/main/plugins/modules/packaging/os/homebrew_cask.py#L830 (for example in https://github.com/ansible-collections/community.crypto/blob/a467f036b1c8c5b35bce9f2d7bace69073c17468/plugins/modules/luks_device.py#L824) does the trick.

**Comment by felixfontein** [comment]
I implemented that in #388.
