### ISSUE TITLE
Where is ACME account data stored on the filesystem?

### ISSUE THREAD

**Issue by lspiehler** [ansible-collections/community.crypto#423]
I can't seem to find where ACME account data is written by this module to the filesystem. Can you please tell me the path?

**Comment by felixfontein** [comment]
You have to specify which module "this module" is.

All modules I can think of require you to specify where you have stored the account key, they do not create or store account keys and account data on disk.

**Comment by lspiehler** [comment]
Forgive me. I'm referring to the community.crypto.acme_account module. I see how to specify the path to the private key, but I'm trying to figure out where the actual acme account information is stored when it successfully registers an account. For example, when the "community.crypto.acme_account_info" module is used, it is reading from wherever the persistent account information is stored. I'm trying to determine where that is. Thank you

**Comment by felixfontein** [comment]
That information is stored by the ACME server. To find out where they store it, you have to check out the server's documentation.

**Comment by lspiehler** [comment]
I understand. I assumed at least some metadata regarding the accounts would be cached on the host like other ACME clients I have experience with, but I can see in the RFC https://datatracker.ietf.org/doc/html/rfc8555#section-7.3.1 that the account URI can be retrieved by making a request to new-account with "onlyReturnExisting": true, and I can see how it is used here:https://github.com/ansible-collections/community.crypto/blob/9e611a614880a98e43ce1aa7be3ce7c53d89f3ea/plugins/module_utils/acme/account.py#L77 Thank you for your help!

**Comment by felixfontein** [comment]
The account URI is also returned by the module, so you can store it somewhere and pass it the next times. The acme_* modules are more like building blocks for building your own ACME solution with Ansible, instead of 'full' clients. This has the huge advantage that you have quite some flexibility on how to integrate this into your system, but obviously it's also more complicated than other clients which simply do some of the work for you :)

**Comment by lspiehler** [comment]
That makes sense. Thanks again for your help.
