### ISSUE TITLE
Add ssh-ed25519 algorithm to openssh_cert types

### ISSUE THREAD

**Issue by bluikko** [ansible-collections/community.crypto#430]
##### SUMMARY

The `openssh_cert` module is lacking the `ssh-ed25519` signature type. #219 mentioned this but only for generating keypairs; but this is a valid algorithm (and a very good one at that) for certificates as well.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

openssh_cert

##### ADDITIONAL INFORMATION

Arguably the best algo available right now.

```yaml

```

**Comment by Ajpantuso** [comment]
Simply specifying a `ed25519` key will ensure that the signature type is `ssh-ed25519`. The `signature_algorithm` option is specific to `RSA` keys which historically have used different algorithms potentially causing compatibility issues between _OpenSSH_ clients and servers (See #276).

Please check the documentation for this option as well as I wrote a summary of the option there as well: https://docs.ansible.com/ansible/latest/collections/community/crypto/openssh_cert_module.html#parameter-signature_algorithm

**Comment by bluikko** [comment]
I had read that comment in the documentation but it only mentioned RSA. I didn't know that not specifying `signature_algorithm` _at all_ will cause it to autodetect.

I guess I did not consider this carefully enough
> Using any value for this option with a non-RSA signing_key will cause this module to fail.

**Comment by bluikko** [comment]
Perhaps a different wording would be more clear - for example something like
> This option can only be used with RSA keys.
