### ISSUE TITLE
openssl_csr missing nameConstraints extension

### ISSUE THREAD

**Issue by spinosae** [ansible-collections/community.crypto#46]
##### SUMMARY

I was trying to limit domains an intermediate CA certificate can sign by adding a `nameConstraints`. However I couldn't find an option for that in `openssl_csr`. Is that implemented?
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

openssl_csr
##### ADDITIONAL INFORMATION

```yaml

```

**Comment by felixfontein** [comment]
It's currently not supported. For the cryptography backend, it should be not very hard to implement (https://cryptography.io/en/latest/x509/reference/#cryptography.x509.NameConstraints). No idea how hard it will be for pyOpenSSL though.
