### ISSUE TITLE
openssh_keypair does not ignore comment as documented

### ISSUE THREAD

**Issue by lucc** [ansible-collections/community.crypto#54]
##### SUMMARY

The docs of the `openssh_keypair` module say about the `comment:` that
> When checking if the key is in the correct state this will be ignored.

but the module checks and updates the comment even if all other parameters are equal.

##### ISSUE TYPE
- Bug Report

(I am reporting this as a bug instead of a documentation bug because I would prefer the documented behaviour over the actual)

##### COMPONENT NAME
openssh_keypair

##### ANSIBLE VERSION
```
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/luc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0]
```

##### CONFIGURATION
```
```
(no change)
##### OS / ENVIRONMENT
Arch Linux

##### STEPS TO REPRODUCE

```yaml
# bug.yml
- hosts: localhost
  tasks:
    - name: create key
      openssh_keypair:
        path: x
        comment: foo
    - name: change comment
      openssh_keypair:
        path: x
        comment: bar
```

##### EXPECTED RESULTS

- on the first run the first task ("create key") should change and the second ("change comment") should be unchanged.
- on subsequent runs (with or without check mode) all tasks should be unchanged.
- in more abstract terms: the module should not change the file on disk if only the comment parameter differs
##### ACTUAL RESULTS
The module changes the file on disk if the comment parameter differs.
```paste below
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [localhost] ****************************************************************

TASK [Gathering Facts] **********************************************************
ok: [localhost]

TASK [create key] ***************************************************************
changed: [localhost]

TASK [change comment] ***********************************************************
changed: [localhost]

PLAY RECAP **********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```

**Comment by felixfontein** [comment]
I guess we forgot to update the docs when we fixed this. Thanks for reporting this!
