### ISSUE TITLE
Can I pass extra arguments to 'community.crypto.openssl_privatekey_convert'?

### ISSUE THREAD

**Issue by p-j-smith** [ansible-collections/community.crypto#570]
##### SUMMARY
- Can I pass `-nocrypt` and `-outform` arguments to `community.crypto.openssl_privatekey_convert`?

##### ISSUE TYPE
- Question

##### COMPONENT NAME
 `community.crypto.openssl_privatekey_convert`

##### ANSIBLE VERSION
```
ansible [core 2.14.1]
  config file = None
  configured module search path = ['/Users/paul/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Caskroom/miniconda/base/envs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/paul/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/Caskroom/miniconda/base/envs/ansible/bin/ansible
  python version = 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:27:35) [Clang 14.0.6 ] (/usr/local/Caskroom/miniconda/base/envs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
# /Users/paul/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.crypto 2.10.0

# /usr/local/Caskroom/miniconda/base/envs/ansible/lib/python3.10/site-packages/ansible_collections
Collection       Version
---------------- -------
community.crypto 2.9.0
```

##### CONFIGURATION

```
CONFIG_FILE() = None
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT

- target OS: Centos 7, Rocky 8

##### STEPS TO REPRODUCE
Hi,

Sorry if this isn't the correct play to be asking questions, I wasn't sure if there's a forum or somewhere better to ask?

I'm currently using `community.crypto` to generate SSL certificates. However, at one step I'm using a `ansible.builtin.command` to convert a private key to pk8 format:

```yaml
ansible.builtin.command: openssl pkcs8 -topk8 -inform PEM -outform DER -nocrypt -in {{ ssl_key_file }} -out {{ ssl_pk8_file }}
```

I would prefer to use the `community.crypto.openssl_privatekey_convert` module to handle this. I've tried:

```yaml
- name: Convert private key to PKCS8 format for use by JDBC
  community.crypto.openssl_privatekey_convert:
    src_path: "{{ ssl_key_file }}"
    dest_path: "{{ ssl_pk8_file }}"
    format: pkcs8
```

But I can't see how to specify `-outform DER` and `-nocrypt`. Is this possible using this module?

Thanks!

**Comment by felixfontein** [comment]
The module does not use the `openssl` binary, so passing options is not possible.

**Comment by p-j-smith** [comment]
Ah I see, okay thanks for the explanation
