### ISSUE TITLE
Ansible documentation refers to incorrect playbook module

### ISSUE THREAD

**Issue by grandiris72** [ansible-collections/community.crypto#588]
##### SUMMARY

[Ansible documentation](https://docs.ansible.com/ansible/latest/collections/community/crypto/openssh_keypair_module.html) claims module is community.crypto.openssh_keypair to call in playbook but the following error is received when calling it: ERROR! 'community.crypto.openssh_keypair' is not a valid attribute for a Play

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

community.crypto.openssh_keypair

##### ANSIBLE VERSION

```paste below
2.11.1
```

**Comment by felixfontein** [comment]
You probably want to read the Ansible documentation on playbooks to figure out how to use modules in playbooks (https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_intro.html#playbook-syntax). The error message you show indicates you tried to use the module at the wrong level.

Also please note that https://groups.google.com/g/ansible-project/ is a better place for such user questions.
