### ISSUE TITLE
Error importing to Automation Hub 2.3

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-collections/community.crypto#605]
##### SUMMARY

When importing this collection into Automation Hub it complains about an invalid license identifier in galaxy.yml

Though I'm not entirely sure this repo is the right place, however, this collection was the only one of all community collections we use that didn't fly.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

n/a

##### COLLECTION VERSION

2.13.0

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT

Automation Hub 2.3

##### STEPS TO REPRODUCE

Try to import on private Automation Hub

##### EXPECTED RESULTS

It to be imported

##### ACTUAL RESULTS

I had to type it from the other system I have the error on as it does not have Internet, so formatting might be a bit screwy.

The error is as follows:

```paste below
Upload of collection failed: Invalid collection metadata. Expecting 'license' to be a list of valid SPDX license identifiers, instead found invalid license identifiers: ''PSF-2.0'' in ''license'' value [''GPL-3.0-or-later'', ''Apache-2.0'', ''BSD-2-Clause'', ''BSD-3-Clause'', ''PSF-2.0'']. For more info, visit https://spdx.org'
```

**Comment by MarkusTeufelberger** [comment]
https://spdx.org/licenses/PSF-2.0.html should be valid, maybe Automation Hub 2.3 has some outdated definitions that don't know this license? Seems more like an issue there tbh.

**Comment by felixfontein** [comment]
The PSF 2.0 license was only added 'recently' to galaxy-importer (and I managed to convince the Galaxy folks to deploy that change to the community Galaxy, see https://github.com/ansible/galaxy-importer/pull/178#issuecomment-1400812114); I'm not sure whether https://github.com/ansible/galaxy-importer/pull/178 made it into an official AH release though...

**Comment by felixfontein** [comment]
galaxy-importer 0.4.6 (https://github.com/ansible/galaxy-importer/commits/eb5ead417c703363beb04d082eb3b2a0767af6fb) supports PSF-2.0. But I don't know how to figure out which AH version includes that one (or a newer one).

**Comment by MarkusTeufelberger** [comment]
Would be great if Red Hat would publish what exactly goes into each release of AH... but then I guess they don't want a situation where people just abandon AWX for a "more closer to the real deal" thing.

**Comment by Thulium-Drake** [comment]
@felixfontein thanks for the reply! I wasn't sure which component handles this in AH :-) but thanks for the pointer. I'll ask the support guys next week when they expect to release an update to AH with that path in it.

And in the mean time, I'll just patch it myself, the patch seems simple enough ;-)

**Comment by felixfontein** [comment]
@Thulium-Drake thanks for checking, I'm also interested in the answer. (I don't use AH, but it would be really good to know...)

Anyway, I've labelled this issue "third-party bug" for now since I consider this a bug (or missing feature) in AH ;-)

**Comment by Thulium-Drake** [comment]
In the mean time I have reported the issue at Red Hat, they've sent it to the engineering team. I'll come around when I have their response :rocket:

**Comment by Thulium-Drake** [comment]
RH Support had the following to say:


> Hello Jeffrey,
> 
> We have got following response from our engineering team,
> 
> ~~~
> galaxy-importer>=0.4.6 supports that license id. I see the conversation is about AAP 2.3 (galaxy_ng 4.6), in galaxy_ng 4.6.5 we allowed support for galaxy-importer 0.4.6 
> 
> > https://github.com/ansible/galaxy_ng/blob/4.6.5/setup.py#L114
> ~~~
> 
> Let us know if you have any further queries with this?
> 
> Regards,

So, it should be made available soon-ish :-) I'll check if there's updates available next time I'm on site.

But for now, case closed!

**Comment by Thulium-Drake** [comment]
> Would be great if Red Hat would publish what exactly goes into each release of AH... but then I guess they don't want a situation where people just abandon AWX for a "more closer to the real deal" thing.

They do, it's here: https://access.redhat.com/support/policy/updates/ansible-automation-platform

Not in super detail, but good enough for most situations :-)

**Comment by felixfontein** [comment]
That's great news! Thanks for sharing the answer :)
