### ISSUE TITLE
Basic management of ssh's `known_hosts` file

### ISSUE THREAD

**Issue by lonix1** [ansible-collections/community.crypto#634]
##### SUMMARY
Support for basic management of ssh's `known_hosts` file.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ssh known hosts

##### ADDITIONAL INFORMATION
I needed to manage a `known_hosts` file, specifically, I had to remove an old key; that can be done using `ssh-keygen -R`. I hoped to do that with `community.crypto.openssh_keypair`, but that seems to work on the keys themselves.

For example, I needed to run this to remove entries with a non-standard port:
```
ssh-keygen -R '[example.com]:2222'
```

And on another host, I needed to remove all entries for a particular server:
```
ssh-keygen -R 'example.com'
```

It would be nice if it were possible to do it via ansible itself, rather than a shell command.

**Comment by MarkusTeufelberger** [comment]
This is already built into ansible-core:

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/known_hosts_module.html
