### ISSUE TITLE
Release of 2.14.1

### ISSUE THREAD

**Issue by genofire** [ansible-collections/community.crypto#635]
here on github it exists, but not on the galaxy:
https://docs.ansible.com/ansible/latest/collections/community/crypto/index.html

**Comment by felixfontein** [comment]
The link you provided is **not** to Ansible Galaxy, but to the docsite of the latest Ansible (PyPI package https://pypi.org/project/ansible/) release (the Galaxy URL is https://galaxy.ansible.com/community/crypto). Ansible releases happen every four weeks, and only then the current latest community.crypto is updated. The next Ansible release will happen next week. So only at that point will the version in the ansible PyPI package, and on the Ansible stable docsite, be updated to 2.14.1 (or whatever the latest community.crypto release is at that point in time).
