### ISSUE TITLE
Add support for adding a custom serial to certificates and csr  ( cmdline: set_serial )

### ISSUE THREAD

**Issue by flybyray** [ansible-collections/community.crypto#77]
##### SUMMARY
Let serial be set in various modules

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
openssl _csr
openssl _certificate

##### ADDITIONAL INFORMATION
some tools require to set special information in certificates. it seems that a `01` serial is required at least for mariadb.
see documentation and automated tests:

https://github.com/mariadb-corporation/mariadb-connector-j/blob/master/.travis/gen-ssl.sh#L69
https://github.com/mariadb-corporation/mariadb-connector-j/blob/master/.travis/gen-ssl.sh#L78
https://github.com/mariadb-corporation/mariadb-connector-j/blob/master/.travis/gen-ssl.sh#L102

**Comment by felixfontein** [comment]
I doubt that MariaDB requires a special serial number. Then you could not use it with a commercial certificate, for example. I assume they set it to 1 so that it is set to a fixed value.

**Comment by flybyray** [comment]
The doubt might be true. I need to further investigate it. But why it is not possible to set custom serial with the modules?

Regarding the doubt:

MySQL commandline client is working with the ansible generated certificates.

But if I import the CA certificate into JKS trust keystore ( Needed for mariadb java connector ). Internal mechanisms say this is not a CA certificate.

```
java.sql.SQLException: No active connection found for master : Could not connect to 10.11.51.11:33912 : PKIX path validation failed: sun.security.validator.ValidatorException: TrustAnchor with subject "..." is not a CA certificate
	at org.mariadb.jdbc.internal.protocol.MasterProtocol.loop(MasterProtocol.java:172)
	at org.mariadb.jdbc.internal.failover.impl.MastersFailoverListener.reconnectFailedConnection(MastersFailoverListener.java:229)
	at org.mariadb.jdbc.internal.failover.impl.MastersFailoverListener.initializeConnection(MastersFailoverListener.java:102)
	at org.mariadb.jdbc.internal.failover.FailoverProxy.<init>(FailoverProxy.java:115)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:554)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:174)
	at org.mariadb.jdbc.Driver.connect(Driver.java:92)
´´´

**Comment by flybyray** [comment]
ok this might be related to: https://access.redhat.com/solutions/4916961 it could be fixed with that environment variable work arround.
trying to add the basic constraint via openssl_csr module

**Comment by felixfontein** [comment]
I can't see what's written on that RedHat page (it's for subscribers only). It looks like you have to set the correct properties for a CA certificate, potentially with
```
      basic_constraints:
      - CA:TRUE
      key_usage:
      - keyCertSign
```
I also think it would be good to have a proper example for this.

Why did you close the issue? I think being able to set `serial` is still a valid feature request, even though it's not needed for the reasons you had in mind.

**Comment by flybyray** [comment]
> I can't see what's written on that RedHat page (it's for subscribers only). 
Actually all can be subscribers. You just need to create a developer account ( it is free ).

>It looks like you have to set the correct properties for a CA certificate, potentially with
> ```
>       basic_constraints:
>       - CA:TRUE
>       key_usage:
>       - keyCertSign
> ```
> 
Exactly! I just added  `CA:TRUE` for `basic_constraints`. Found that in test cases already used by this repo.

> I also think it would be good to have a proper example for this.
Proper examples are most of the time things which are tested by automated tests.

> Why did you close the issue? I think being able to set `serial` is still a valid feature request, even though it's not needed for the reasons you had in mind.
I am not sure why. Just did not want to waste resources? Maybe the serial is not so important and I hope there are a lot of best effort/practice related enhancements in this module. I believe stuff like this would be more part of CA providers ( and here most probably only selfsigned/ownca ). Some hints about a `serial` are only found in the openssl_csr module https://docs.ansible.com/ansible/latest/modules/openssl_csr_module.html#openssl-csr-module .

**Comment by MarkusTeufelberger** [comment]
The setting in the CSR is something different by the way (used to choose the certificate that you want a CA to use as issuer - which they can do or ignore). It is not used to request a certain serial number for the resulting certificate, that's up for the CA to decide.

As you said, there might be a case to add a serial parameter to selfsigned/ownca providers in `x509_certificate` to make operation a bit more idempotent. It also offers users some serious opportunities to mess up. Unfortunately there's no real "expert mode" for Ansible modules, so not every possible setting was implemented from the get-go to cover the first 90% of use cases. Don't let that stop you from asking for parameters you're missing (even if they weren't the ones that would have solved your issue in this case). :-)
