### ISSUE TITLE
Renaming master branch to main on Thursday, July 2nd

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.crypto#80]
### Renaming `master` branch to `main` on Thursday, July 2nd

The Ansible team decided to rename the `master` branch in all Ansible-controlled collections to `main` (see ansible-collections/overview#83 and ansible-collections/overview#87 for history and more information). This also applies to `community.crypto`. My suggestion would be to do this now as well, before the 1.0.0 release, especially since the `master` branch is mentioned in the README (link to the changelog). We will change the branch for this repository tomorrow (Thursday, July 2nd) afternoon (Europe).

At https://github.com/ansible/community/wiki/Changing-the-git-default-branch-to-main#updating-local-clones you can find instructions on how to update your forks and local checkouts. If you have created a pull request, there is nothing you need to do - we will retarget the pull requests so they will get merged to `master` and not to `main`.

If you have questions, please reach out to us on #ansible-community (Freenode).

CC @abadger @Akasurde @Andersson007 @ctrufan @eric-belhomme @gundalow @jborean93 @lucc @MarkusTeufelberger @moreati @mulatinho @nkakouros-forks @puiterwijk @relrod @s-hertel @samccann @Shaps @Spredzy (you all forked this repository or are otherwise related to it)

**Comment by MarkusTeufelberger** [comment]
SVN was right all along with `trunk`! :-D

Personally I really do not see a lot of agreement with that plan in https://github.com/ansible-collections/overview/issues/83 other than Ansible's "lot of internal staff" supporting it and just pushing it through, on the other hand I just don't care enough about branch names in some source control tool to waste energy discussing this. The only minor inconvenience will be to make sure I don't pull from "master" but "main"...

All in all: ¯\\\_(ツ)\_/¯ - maybe it keeps a certain class of jerks away?

**Comment by felixfontein** [comment]
If you prefer SVN: https://svnhub.com/ ;-) (never tried it, and not sure I actually want to)

About the discussion: it looks a lot less controversial to me when ignoring all people in the discussion that do not really seem related to Ansible and the collections. In the end, the Ansible team decided (since that happened internally I have no idea how much controversy it was there and how the opposition to this subject in that issue was weighted), and the amount of work that this change resolves in is minimal (at least for the collections I'm involved in). Also it is a good reminder to see in which places the default branch name is actually hardcoded (and a chance to reduce that, if possible - in this repo I think it's already quite minimal IMO).

**Comment by felixfontein** [comment]
Switch is in progress...

**Comment by felixfontein** [comment]
...and done! :)

**Comment by felixfontein** [comment]
Please don't forget to adjust your forks (you'd at least want to get `main` there as well).
